In [15]:
import pandas as pd
# 1. Quitar el límite de filas 
pd.set_option('display.max_rows', 344)

# 2. Quitar el límite de columnas
pd.set_option('display.max_columns', 20)

# 3. Mostrar el contenido de las celdas sin recortar el texto
pd.set_option('display.max_colwidth', 100)

In [16]:
tabla = pd.read_csv("penguins_raw.csv")
tabla.head(344)

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
5,PAL0708,6,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A2,Yes,2007-11-16,39.3,20.6,190.0,3650.0,MALE,8.66496,-25.29805,NaN
6,PAL0708,7,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N4A1,No,2007-11-15,38.9,17.8,181.0,3625.0,FEMALE,9.18718,-25.21799,Nest never observed with full clutch.
7,PAL0708,8,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N4A2,No,2007-11-15,39.2,19.6,195.0,4675.0,MALE,9.46060,-24.89958,Nest never observed with full clutch.
8,PAL0708,9,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N5A1,Yes,2007-11-09,34.1,18.1,193.0,3475.0,NaN,NaN,NaN,No blood sample obtained.
9,PAL0708,10,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N5A2,Yes,2007-11-09,42.0,20.2,190.0,4250.0,NaN,9.13362,-25.09368,No blood sample obtained for sexing.
10,PAL0708,11,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N6A1,Yes,2007-11-09,37.8,17.1,186.0,3300.0,NaN,8.63243,-25.21315,No blood sample obtained for sexing.
11,PAL0708,12,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N6A2,Yes,2007-11-09,37.8,17.3,180.0,3700.0,NaN,NaN,NaN,No blood sample obtained.
12,PAL0708,13,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N7A1,Yes,2007-11-15,41.1,17.6,182.0,3200.0,FEMALE,NaN,NaN,Not enough blood for isotopes.
13,PAL0708,14,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N7A2,Yes,2007-11-15,38.6,21.2,191.0,3800.0,MALE,NaN,NaN,Not enough blood for isotopes.
14,PAL0708,15,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N8A1,Yes,2007-11-16,34.6,21.1,198.0,4400.0,MALE,8.55583,-25.22588,NaN
15,PAL0708,16,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N8A2,Yes,2007-11-16,36.6,17.8,185.0,3700.0,FEMALE,NaN,NaN,Not enough blood for isotopes.
16,PAL0708,17,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N9A1,Yes,2007-11-12,38.7,19.0,195.0,3450.0,FEMALE,9.18528,-25.06691,NaN
17,PAL0708,18,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N9A2,Yes,2007-11-12,42.5,20.7,197.0,4500.0,MALE,8.67538,-25.13993,NaN
18,PAL0708,19,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N10A1,Yes,2007-11-16,34.4,18.4,184.0,3325.0,FEMALE,8.47827,-25.23319,NaN
19,PAL0708,20,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N10A2,Yes,2007-11-16,46.0,21.5,194.0,4200.0,MALE,9.11616,-24.77227,NaN
20,PAL0708,21,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N11A1,Yes,2007-11-12,37.8,18.3,174.0,3400.0,FEMALE,8.73762,-25.09383,NaN
21,PAL0708,22,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N11A2,Yes,2007-11-12,37.7,18.7,180.0,3600.0,MALE,8.66271,-25.06390,NaN
22,PAL0708,23,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N12A1,Yes,2007-11-12,35.9,19.2,189.0,3800.0,FEMALE,9.22286,-25.03474,NaN
23,PAL0708,24,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N12A2,Yes,2007-11-12,38.2,18.1,185.0,3950.0,MALE,8.43423,-25.22664,NaN
24,PAL0708,25,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N13A1,Yes,2007-11-10,38.8,17.2,180.0,3800.0,MALE,9.63954,-25.29856,NaN
25,PAL0708,26,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N13A2,Yes,2007-11-10,35.3,18.9,187.0,3800.0,FEMALE,9.21292,-24.36130,NaN
26,PAL0708,27,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N17A1,Yes,2007-11-12,40.6,18.6,183.0,3550.0,MALE,8.93997,-25.36288,NaN
27,PAL0708,28,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N17A2,Yes,2007-11-12,40.5,17.9,187.0,3200.0,FEMALE,8.08138,-25.49448,NaN
28,PAL0708,29,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N18A1,No,2007-11-10,37.9,18.6,172.0,3150.0,FEMALE,8.38404,-25.19837,Nest never observed with full clutch.
29,PAL0708,30,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N18A2,No,2007-11-10,40.5,18.9,180.0,3950.0,MALE,8.90027,-25.11609,Nest never observed with full clutch.
30,PAL0708,31,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N21A1,Yes,2007-11-09,39.5,16.7,178.0,3250.0,FEMALE,9.69756,-25.11223,NaN
31,PAL0708,32,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N21A2,Yes,2007-11-09,37.2,18.1,178.0,3900.0,MALE,9.72764,-25.01020,NaN
32,PAL0708,33,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N22A1,Yes,2007-11-09,39.5,17.8,188.0,3300.0,FEMALE,9.66523,-25.06020,NaN
33,PAL0708,34,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N22A2,Yes,2007-11-09,40.9,18.9,184.0,3900.0,MALE,8.79665,-25.14591,NaN
34,PAL0708,35,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N23A1,Yes,2007-11-16,36.4,17.0,195.0,3325.0,FEMALE,9.17847,-25.23061,NaN
35,PAL0708,36,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N23A2,Yes,2007-11-16,39.2,21.1,196.0,4150.0,MALE,9.15308,-25.03469,NaN
36,PAL0708,37,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N24A1,Yes,2007-11-16,38.8,20.0,190.0,3950.0,MALE,9.18985,-25.12255,NaN
37,PAL0708,38,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N24A2,Yes,2007-11-16,42.2,18.5,180.0,3550.0,FEMALE,8.04787,-25.49523,NaN
38,PAL0708,39,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N25A1,No,2007-11-13,37.6,19.3,181.0,3300.0,FEMALE,9.41131,-25.04169,Nest never observed with full clutch.
39,PAL0708,40,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N25A2,No,2007-11-13,39.8,19.1,184.0,4650.0,MALE,NaN,NaN,Nest never observed with full clutch. Not enough blood for isotopes.
40,PAL0708,41,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N26A1,Yes,2007-11-16,36.5,18.0,182.0,3150.0,FEMALE,9.68933,-24.42280,NaN
41,PAL0708,42,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N26A2,Yes,2007-11-16,40.8,18.4,195.0,3900.0,MALE,NaN,NaN,Not enough blood for isotopes.
42,PAL0708,43,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N27A1,Yes,2007-11-19,36.0,18.5,186.0,3100.0,FEMALE,9.50772,-25.03492,NaN
43,PAL0708,44,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N27A2,Yes,2007-11-19,44.1,19.7,196.0,4400.0,MALE,9.23720,-24.52698,NaN
44,PAL0708,45,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N28A1,Yes,2007-11-16,37.0,16.9,185.0,3000.0,FEMALE,9.36392,-25.01745,NaN
45,PAL0708,46,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N28A2,Yes,2007-11-16,39.6,18.8,190.0,4600.0,MALE,9.49106,-24.10255,NaN
46,PAL0708,47,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N29A1,Yes,2007-11-13,41.1,19.0,182.0,3425.0,MALE,NaN,NaN,Not enough blood for isotopes.
47,PAL0708,48,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N29A2,Yes,2007-11-13,37.5,18.9,179.0,2975.0,NaN,NaN,NaN,Sexing primers did not amplify. Not enough blood for isotopes.
48,PAL0708,49,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N30A1,Yes,2007-11-13,36.0,17.9,190.0,3450.0,FEMALE,9.51784,-25.07683,NaN
49,PAL0708,50,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N30A2,Yes,2007-11-13,42.3,21.2,191.0,4150.0,MALE,8.87988,-25.18543,NaN
50,PAL0809,51,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N21A1,Yes,2008-11-06,39.6,17.7,186.0,3500.0,FEMALE,8.46616,-26.12989,NaN
51,PAL0809,52,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N21A2,Yes,2008-11-06,40.1,18.9,188.0,4300.0,MALE,8.51362,-26.55602,NaN
52,PAL0809,53,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N22A1,Yes,2008-11-09,35.0,17.9,190.0,3450.0,FEMALE,8.19539,-26.17213,NaN
53,PAL0809,54,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N22A2,Yes,2008-11-09,42.0,19.5,200.0,4050.0,MALE,8.48095,-26.31460,NaN
54,PAL0809,55,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N23A1,Yes,2008-11-09,34.5,18.1,187.0,2900.0,FEMALE,8.41837,-26.54718,NaN
55,PAL0809,56,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N23A2,Yes,2008-11-09,41.4,18.6,191.0,3700.0,MALE,8.35396,-26.27853,NaN
56,PAL0809,57,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N24A1,Yes,2008-11-15,39.0,17.5,186.0,3550.0,FEMALE,8.57199,-26.07188,NaN
57,PAL0809,58,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N24A2,Yes,2008-11-15,40.6,18.8,193.0,3800.0,MALE,8.56674,-25.98843,NaN
58,PAL0809,59,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N25A1,Yes,2008-11-15,36.5,16.6,181.0,2850.0,FEMALE,9.07878,-25.88156,NaN
59,PAL0809,60,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N25A2,Yes,2008-11-15,37.6,19.1,194.0,3750.0,MALE,9.10800,-25.89677,NaN
60,PAL0809,61,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N27A1,Yes,2008-11-13,35.7,16.9,185.0,3150.0,FEMALE,8.96472,-26.40943,NaN
61,PAL0809,62,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N27A2,Yes,2008-11-13,41.3,21.1,195.0,4400.0,MALE,8.74802,-26.37809,NaN
62,PAL0809,63,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N28A1,Yes,2008-11-13,37.6,17.0,185.0,3600.0,FEMALE,8.58063,-26.21569,NaN
63,PAL0809,64,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N28A2,Yes,2008-11-13,41.1,18.2,192.0,4050.0,MALE,8.62264,-26.60023,NaN
64,PAL0809,65,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N29A1,Yes,2008-11-13,36.4,17.1,184.0,2850.0,FEMALE,8.62623,-26.11650,NaN
65,PAL0809,66,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N29A2,Yes,2008-11-13,41.6,18.0,192.0,3950.0,MALE,8.85562,-26.09294,NaN
66,PAL0809,67,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N30A1,Yes,2008-11-06,35.5,16.2,195.0,3350.0,FEMALE,8.56192,-25.95541,NaN
67,PAL0809,68,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N30A2,Yes,2008-11-06,41.1,19.1,188.0,4100.0,MALE,8.71078,-25.81012,NaN
68,PAL0809,69,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N32A1,No,2008-11-11,35.9,16.6,190.0,3050.0,FEMALE,8.47781,-26.07821,Nest never observed with full clutch.
69,PAL0809,70,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N32A2,No,2008-11-11,41.8,19.4,198.0,4450.0,MALE,8.86853,-26.06209,Nest never observed with full clutch.
70,PAL0809,71,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N34A1,Yes,2008-11-14,33.5,19.0,190.0,3600.0,FEMALE,7.88863,-26.63085,NaN
71,PAL0809,72,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N34A2,Yes,2008-11-14,39.7,18.4,190.0,3900.0,MALE,9.29808,-25.23453,NaN
72,PAL0809,73,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N35A1,Yes,2008-11-11,39.6,17.2,196.0,3550.0,FEMALE,8.33524,-26.55351,NaN
73,PAL0809,74,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N35A2,Yes,2008-11-11,45.8,18.9,197.0,4150.0,MALE,8.18658,-26.45978,NaN
74,PAL0809,75,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N36A1,Yes,2008-11-08,35.5,17.5,190.0,3700.0,FEMALE,8.70642,-26.15003,NaN
75,PAL0809,76,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N36A2,Yes,2008-11-08,42.8,18.5,195.0,4250.0,MALE,8.29930,-26.38986,NaN
76,PAL0809,77,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N37A1,Yes,2008-11-06,40.9,16.8,191.0,3700.0,FEMALE,8.47257,-26.02002,NaN
77,PAL0809,78,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N37A2,Yes,2008-11-06,37.2,19.4,184.0,3900.0,MALE,8.35540,-26.44787,NaN
78,PAL0809,79,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N38A1,Yes,2008-11-09,36.2,16.1,187.0,3550.0,FEMALE,7.82381,-26.51382,NaN
79,PAL0809,80,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N38A2,Yes,2008-11-09,42.1,19.1,195.0,4000.0,MALE,9.05736,-25.81513,NaN
80,PAL0809,81,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N39A1,Yes,2008-11-02,34.6,17.2,189.0,3200.0,FEMALE,7.69778,-26.53870,NaN
81,PAL0809,82,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N39A2,Yes,2008-11-02,42.9,17.6,196.0,4700.0,MALE,8.63259,-26.23027,NaN
82,PAL0809,83,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N40A1,Yes,2008-11-07,36.7,18.8,187.0,3800.0,FEMALE,7.88494,-26.24837,NaN
83,PAL0809,84,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N40A2,Yes,2008-11-07,35.1,19.4,193.0,4200.0,MALE,8.90002,-26.46254,NaN
84,PAL0809,85,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N41A1,Yes,2008-11-17,37.3,17.8,191.0,3350.0,FEMALE,8.32718,-26.38396,NaN
85,PAL0809,86,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N41A2,Yes,2008-11-17,41.3,20.3,194.0,3550.0,MALE,9.14863,-26.09635,NaN
86,PAL0809,87,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N42A1,Yes,2008-11-08,36.3,19.5,190.0,3800.0,MALE,8.57087,-26.22227,NaN
87,PAL0809,88,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N42A2,Yes,2008-11-08,36.9,18.6,189.0,3500.0,FEMALE,8.59147,-26.08165,NaN
88,PAL0809,89,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N44A1,Yes,2008-11-08,38.3,19.2,189.0,3950.0,MALE,9.07826,-26.12417,NaN
89,PAL0809,90,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N44A2,Yes,2008-11-08,38.9,18.8,190.0,3600.0,FEMALE,8.36936,-26.11199,NaN
90,PAL0809,91,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N45A1,Yes,2008-11-14,35.7,18.0,202.0,3550.0,FEMALE,8.46531,-26.05621,NaN
91,PAL0809,92,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N45A2,Yes,2008-11-14,41.1,18.1,205.0,4300.0,MALE,8.77018,-25.83352,NaN
92,PAL0809,93,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N46A1,Yes,2008-11-05,34.0,17.1,185.0,3400.0,FEMALE,8.01485,-26.69543,NaN
93,PAL0809,94,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N46A2,Yes,2008-11-05,39.6,18.1,186.0,4450.0,MALE,8.49915,-26.42406,NaN
94,PAL0809,95,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N48A1,Yes,2008-11-17,36.2,17.3,187.0,3300.0,FEMALE,8.90723,-26.30037,NaN
95,PAL0809,96,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N48A2,Yes,2008-11-17,40.8,18.9,208.0,4300.0,MALE,8.48204,-26.57941,NaN
96,PAL0809,97,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N49A1,Yes,2008-11-08,38.1,18.6,190.0,3700.0,FEMALE,8.10277,-26.50086,NaN
97,PAL0809,98,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N49A2,Yes,2008-11-08,40.3,18.5,196.0,4350.0,MALE,8.39459,-26.01152,NaN
98,PAL0809,99,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N50A1,Yes,2008-11-10,33.1,16.1,178.0,2900.0,FEMALE,9.04218,-26.15775,NaN
99,PAL0809,100,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N50A2,Yes,2008-11-10,43.2,18.5,192.0,4100.0,MALE,8.97025,-26.03679,NaN
100,PAL0910,101,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N47A1,Yes,2009-11-09,35.0,17.9,192.0,3725.0,FEMALE,8.84451,-26.28055,NaN
101,PAL0910,102,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N47A2,Yes,2009-11-09,41.0,20.0,203.0,4725.0,MALE,9.01079,-26.38085,NaN
102,PAL0910,103,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N49A1,Yes,2009-11-15,37.7,16.0,183.0,3075.0,FEMALE,9.21510,-26.22530,NaN
103,PAL0910,104,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N49A2,Yes,2009-11-15,37.8,20.0,190.0,4250.0,MALE,9.51929,-25.69199,NaN
104,PAL0910,105,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N51A1,Yes,2009-11-15,37.9,18.6,193.0,2925.0,FEMALE,9.02642,-25.86482,NaN
105,PAL0910,106,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N51A2,Yes,2009-11-15,39.7,18.9,184.0,3550.0,MALE,8.85699,-25.80208,NaN
106,PAL0910,107,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N53A1,Yes,2009-11-15,38.6,17.2,199.0,3750.0,FEMALE,8.77322,-26.48973,NaN
107,PAL0910,108,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N53A2,Yes,2009-11-15,38.2,20.0,190.0,3900.0,MALE,9.59245,-25.70711,NaN
108,PAL0910,109,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N55A1,Yes,2009-11-20,38.1,17.0,181.0,3175.0,FEMALE,9.79532,-25.27385,NaN
109,PAL0910,110,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N55A2,Yes,2009-11-20,43.2,19.0,197.0,4775.0,MALE,9.31735,-25.45171,NaN
110,PAL0910,111,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N58A1,Yes,2009-11-12,38.1,16.5,198.0,3825.0,FEMALE,8.43951,-26.57563,NaN
111,PAL0910,112,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N58A2,Yes,2009-11-12,45.6,20.3,191.0,4600.0,MALE,8.65466,-26.32909,NaN
112,PAL0910,113,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N60A1,Yes,2009-11-15,39.7,17.7,193.0,3200.0,FEMALE,9.02657,-26.06203,NaN
113,PAL0910,114,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N60A2,Yes,2009-11-15,42.2,19.5,197.0,4275.0,MALE,8.80186,-26.41218,NaN
114,PAL0910,115,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N61A1,Yes,2009-11-17,39.6,20.7,191.0,3900.0,FEMALE,8.80967,-26.78958,NaN
115,PAL0910,116,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N61A2,Yes,2009-11-17,42.7,18.3,196.0,4075.0,MALE,8.91434,-26.42018,NaN
116,PAL0910,117,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N63A1,Yes,2009-11-18,38.6,17.0,188.0,2900.0,FEMALE,9.18021,-25.77264,NaN
117,PAL0910,118,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N63A2,Yes,2009-11-18,37.3,20.5,199.0,3775.0,MALE,9.49645,-26.36678,NaN
118,PAL0910,119,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N64A1,Yes,2009-11-22,35.7,17.0,189.0,3350.0,FEMALE,8.96436,-23.90309,NaN
119,PAL0910,120,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N64A2,Yes,2009-11-22,41.1,18.6,189.0,3325.0,MALE,9.32277,-26.09989,NaN
120,PAL0910,121,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N66A1,No,2009-11-17,36.2,17.2,187.0,3150.0,FEMALE,9.04296,-26.19444,Nest never observed with full clutch.

In [28]:
tabla_limpia = tabla.dropna(how="all")
tabla.dropna()

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
6,PAL0708,7,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N4A1,No,2007-11-15,38.9,17.8,181.0,3625.0,FEMALE,9.18718,-25.21799,Nest never observed with full clutch.
7,PAL0708,8,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N4A2,No,2007-11-15,39.2,19.6,195.0,4675.0,MALE,9.46060,-24.89958,Nest never observed with full clutch.
28,PAL0708,29,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N18A1,No,2007-11-10,37.9,18.6,172.0,3150.0,FEMALE,8.38404,-25.19837,Nest never observed with full clutch.
29,PAL0708,30,Adelie Penguin (Pygoscelis adeliae),Anvers,Biscoe,"Adult, 1 Egg Stage",N18A2,No,2007-11-10,40.5,18.9,180.0,3950.0,MALE,8.90027,-25.11609,Nest never observed with full clutch.
38,PAL0708,39,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N25A1,No,2007-11-13,37.6,19.3,181.0,3300.0,FEMALE,9.41131,-25.04169,Nest never observed with full clutch.
68,PAL0809,69,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N32A1,No,2008-11-11,35.9,16.6,190.0,3050.0,FEMALE,8.47781,-26.07821,Nest never observed with full clutch.
69,PAL0809,70,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N32A2,No,2008-11-11,41.8,19.4,198.0,4450.0,MALE,8.86853,-26.06209,Nest never observed with full clutch.
120,PAL0910,121,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N66A1,No,2009-11-17,36.2,17.2,187.0,3150.0,FEMALE,9.04296,-26.19444,Nest never observed with full clutch.
121,PAL0910,122,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N66A2,No,2009-11-17,37.7,19.8,198.0,3500.0,MALE,9.11066,-26.42563,Nest never observed with full clutch.
130,PAL0910,131,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N73A1,No,2009-11-23,38.5,17.9,190.0,3325.0,FEMALE,8.98460,-25.57956,Nest never observed with full clutch.
131,PAL0910,132,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N73A2,No,2009-11-23,43.1,19.2,197.0,3500.0,MALE,8.86495,-26.13960,Nest never observed with full clutch.
138,PAL0910,139,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N79A1,No,2009-11-16,37.0,16.5,185.0,3400.0,FEMALE,8.61651,-26.07021,Nest never observed with full clutch.
139,PAL0910,140,Adelie Penguin (Pygoscelis adeliae),Anvers,Dream,"Adult, 1 Egg Stage",N79A2,No,2009-11-16,39.7,17.9,193.0,4250.0,MALE,9.25769,-25.88798,Nest never observed with full clutch.
162,PAL0708,11,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N36A1,No,2007-11-27,40.9,13.7,214.0,4650.0,FEMALE,8.19579,-25.39330,Nest never observed with full clutch.
163,PAL0708,12,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N36A2,No,2007-11-27,49.0,16.1,216.0,5550.0,MALE,8.10417,-25.50562,Nest never observed with full clutch.
192,PAL0809,41,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N6A1,No,2008-11-04,42.7,13.7,208.0,3950.0,FEMALE,8.14567,-26.59467,Nest never observed with full clutch.
193,PAL0809,42,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N6A2,No,2008-11-04,49.6,16.0,225.0,5700.0,MALE,8.38324,-26.84272,Nest never observed with full clutch.
198,PAL0809,47,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N11A1,No,2008-11-09,45.5,13.9,210.0,4200.0,FEMALE,8.47829,-26.61788,Nest never observed with full clutch.
199,PAL0809,48,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N11A2,No,2008-11-09,50.5,15.9,225.0,5400.0,MALE,8.65803,-26.57585,Nest never observed with full clutch.
270,PAL0910,119,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N38A1,No,2009-12-01,47.2,13.7,214.0,4925.0,FEMALE,7.99184,-26.20538,Nest never observed with full clutch.
276,PAL0708,1,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N61A1,No,2007-11-19,46.5,17.9,192.0,3500.0,FEMALE,9.03935,-24.30229,Nest never observed with full clutch.
277,PAL0708,2,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N61A2,No,2007-11-19,50.0,19.5,196.0,3900.0,MALE,8.92069,-24.23592,Nest never observed with full clutch.
292,PAL0708,17,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N71A1,No,2007-11-30,50.3,20.0,197.0,3300.0,MALE,10.02019,-24.54704,Nest never observed with full clutch.
293,PAL0708,18,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N71A2,No,2007-11-30,58.0,17.8,181.0,3700.0,FEMALE,9.14382,-24.57994,Nest never observed with full clutch.
298,PAL0708,23,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N85A1,No,2007-11-28,43.2,16.6,187.0,2900.0,FEMALE,9.35416,-25.01185,Nest never observed with full clutch.
299,PAL0708,24,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N85A2,No,2007-11-28,50.6,19.4,193.0,3800.0,MALE,9.28153,-24.97134,Nest never observed with full clutch.
300,PAL0708,25,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N89A1,No,2007-11-28,46.7,17.9,195.0,3300.0,FEMALE,9.74144,-24.59467,Nest never observed with full clutch.
301,PAL0708,26,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N89A2,No,2007-11-28,52.0,19.0,197.0,4150.0,MALE,9.36799,-24.47142,Nest never observed with full clutch.
302,PAL0809,27,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N61A1,No,2008-11-25,50.5,18.4,200.0,3400.0,FEMALE,8.93990,-23.89017,Nest never observed with full clutch.
303,PAL0809,28,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N61A2,No,2008-11-25,49.5,19.0,200.0,3800.0,MALE,9.63074,-24.34684,Nest never observed with full clutch.
314,PAL0809,39,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N72A1,No,2008-11-24,46.9,16.6,192.0,2700.0,FEMALE,9.80589,-24.73735,Nest never observed with full clutch.
315,PAL0809,40,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N72A2,No,2008-11-24,53.5,19.9,205.0,4500.0,MALE,10.02544,-24.90816,Nest never observed with full clutch.
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A1,No,2009-11-21,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A2,No,2009-11-21,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.